### ISSUE TITLE
Logstash-plugin-date cover nginx time_local to @timestamp incorrect

### ISSUE THREAD

**Issue by asd80703406** [logstash-plugins/logstash-filter-date#104]
- Version: logstash - 5.4.0
- Operating System: CentOS release 6.6 (Final)
- Config File (if you have sensitive info, please remove it):
**input {
    file {
        path => "/mnt/nginx/access.log"
        #start_position => ""
        sincedb_path => "/tmp/.sincedb"
    }
}
filter {
    ruby {
       init => "@kname = ['remote_addr','http_x_forwarded_for','country','city','time_local','server_name','request','request_length','request_time','uid_set','uid_got','status','body_bytes_sent','bytes_sent','connection','connection_requests','http_user_agent','http_referer','upstream_addr','upstream_status','upstream_response_time', 'http_Authorization']"
        code => "
            new_event = LogStash::Event.new(Hash[@kname.zip(event.get('message').split('||'))])
            new_event.remove('@timestamp')
            event.append(new_event)"
    }
    if [request] {
        ruby {
            init => "@kname = ['method', 'uri', 'httpver']"
            code =>"
                    new_event = LogStash::Event.new(Hash[@kname.zip(event.get('request').split(' '))])
                    new_event.remove('@timestamp')
                    event.append(new_event)
                "
        }
        if [uri] {
            ruby {
                init => "@kname = ['url_path', 'url_args']"
                code =>"
                    new_event = LogStash::Event.new(Hash[@kname.zip(event.get('uri').split('?'))])
                    new_event.remove('@timestamp')
                    event.append(new_event)
                    "
            }
                kv {
                    prefix => "url_"
                    source => "url_args"
                    field_split => "&"
                    include_keys => ["device", "deviceId", "appVer", "platform", "lang", "osVer"]
                    remove_field => ['url_args', 'uri', 'request', 'path', 'connection']
                }
        }
    
    }
    mutate {
        convert => {"request_length" => "integer" }
        convert => { "status" => "integer"}
        convert => { "bytes_sent" => "integer"}
        convert => { "upstream_status" => "integer"}
        convert => { "request_time" => "float"}
        convert => { "upstream_response_time" => "float"}
    }
    date {
        match => ["time_local" , "dd/MMM/yyyy:hh:mm:ss Z"]
        target => "@timestamp"
        timezone => "Asia/Shanghai"
    }
}

output {
    elasticsearch {
        hosts => ["http://172.28.49.22:9200"]
        index => "nginx-frontend-accesslog-%{+YYYY.MM.dd}" 
        
    }   
    stdout { codec => rubydebug }
}**
- Sample Data: 
nginx logconfig:
log_format rectoken '$remote_addr||$http_x_forwarded_for||$geoip_country_code||$geoip_city||$time_local'
                    '||$server_name||$request||$request_length||$request_time||$uid_set||$uid_got'
                    '||$status||$body_bytes_sent||$bytes_sent||$connection||$connection_requests'
               '||$http_user_agent||$http_referer||$upstream_addr||$upstream_status||$upstream_response_time||$http_Authorization';
Log sample:
117.36.153.238||-||CN||Xian||20/Jun/2017:12:22:07 +0800||frontend.xxxx.com||GET /v6/user/messages/preview?vendor=online&osVer=6.0.1&platform=android&appName=xxx&appVer=5.2.2&device=Redmi%204&deviceId=be77e483-0465-456e-81f4-823b508d5512&screenH=1920&skin=2&screenW=1080&lang=zh_CN HTTP/1.1||425||0.093||ngxid=3E22FA7CDF944859345CEF3002BAC405||-||200||257||964||8806088458||1||okhttp/3.6.0||-||172.28.48.85:8080||200||0.093||Bearer 0t0AmqMkEXA0yHSGgrQhJm2DfwcF1g

- Steps to Reproduce:
        As usually，my logstash run fine and push log to es correct. But when the time is betweet "12:00"  and "13:00", it can't cover localtime “20/Jun/2017:12:22:07 +0800” to timestamp correct and it will make timestamp to "2017-06-19T16:22:07"  which expect as to "2017-06-20T12:22:07".  Every log betweet "12:00"  and "13:00" is wrong so that my kibana can't find any log betweet "12:00"  and "13:00"。 I had tried many times, but nothing to do .

**Comment by asd80703406** [comment]
Someone？

**Comment by jordansissel** [comment]
You might find better result for this question on https://discuss.elastic.co/

I have not read the issue fully (I haven't had time to do so), but from a quick glance, it looks like this might be a configuration issue that our greater community of users could help with. It may not be a bug, I don't know, but https://discuss.elastic.co/ would be a good starting place to ask. :)
