### ISSUE TITLE
Failure parsing ISO8601 date from Java logs

### ISSUE THREAD

**Issue by hakman** [logstash-plugins/logstash-filter-date#17]
Java loggers print ISO8601 dates in a several ways:
* [log4j](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/helpers/ISO8601DateFormat.html) - %d{ISO8601} => 2015-04-23 10:28:39**,**084
* [logback](http://logback.qos.ch/manual/layouts.html) - %date{ISO8601} => 2006-10-20 14:06:49**,**812 (same as log4j)
* [log4j2]() - %d{ISO8601} => 2012-11-02**T**14:34:02**,**781

Logstash fails to parse the following dates in the date filter because it expects the fraction of second to be separated by a "." instead of a ",":
> Failed parsing date from field {:field=>"timestamp", :value=>"2015-04-23 10:28:39,084", :exception=>java.lang.IllegalArgumentException: Invalid format: "2015-04-23 10:28:39,084" is malformed at ",084", :level=>:warn}

This can be easily fixed by adding some entries to the [almostISOparsers](https://github.com/logstash-plugins/logstash-filter-date/blob/master/lib/logstash/filters/date.rb#L134) list.
I tested this approach with Logstash 1.5 RC3.

Thank you for the great work you are doing with Logstash. Looking forward to seeing 1.5 released.

**Comment by purbon** [comment]
@hakman thanks for your report, this is actually a nice issue as ISO8601 actually allow both as separators for fractions, so both should be accepted.

**Comment by purbon** [comment]
however acording to http://joda-time.sourceforge.net/apidocs/src-html/org/joda/time/format/ISODateTimeFormat.html#line.774, the method used to create the ISO8601 parser this should understand commas as separators.

**Comment by purbon** [comment]
I see this issue more about Joda, the internal library used, that require T as a separator between the time and date. According to the ISO standard,

> By mutual agreement of the partners in information interchange, the character [T] may be omitted in applications where there is no risk of confusing a date and time of day representation with others defined in this International Standard.

**Comment by hakman** [comment]
@purbon Thanks for fixing this!

**Comment by purbon** [comment]
you're welcome. waiting to finish some other work in here and I will release a new version of the plugin.

**Comment by runningman84** [comment]
Any ETA for a release here?

**Comment by jsvd** [comment]
the current version of this plugin (2.1.1) includes the fix for this:

```
/tmp/logstash-2.1.1 % bin/plugin list --verbose | grep date
logstash-filter-date (2.0.2)
/tmp/logstash-2.1.1 % echo "2016-01-05 16:04:23,445" | bin/logstash -e 'input { stdin { } } filter { date { match => [ "message", "ISO8601" ] } }'
Settings: Default filter workers: 2
Logstash startup completed
Failed parsing date from field {:field=>"message", :value=>"2016-01-05 16:04:23,445", :exception=>"Invalid format: \"2016-01-05 16:04:23,445\" is malformed at \",445\"", :config_parsers=>"ISO8601", :config_locale=>"default=en_US", :level=>:warn}
{
       "message" => "2016-01-05 16:04:23,445",
      "@version" => "1",
    "@timestamp" => "2016-01-07T11:28:06.436Z",
          "host" => "Joaos-MBP.lan",
          "tags" => [
        [0] "_dateparsefailure"
    ]
}
Logstash shutdown completed
/tmp/logstash-2.1.1 % bin/plugin update logstash-filter-date
Updating logstash-filter-date
Updated logstash-filter-date 2.0.2 to 2.1.1
/tmp/logstash-2.1.1 % echo "2016-01-05 16:04:23,445" | bin/logstash -e 'input { stdin { } } filter { date { match => [ "message", "ISO8601" ] } }'
Settings: Default filter workers: 2
Logstash startup completed
{
       "message" => "2016-01-05 16:04:23,445",
      "@version" => "1",
    "@timestamp" => "2016-01-05T16:04:23.445Z",
          "host" => "Joaos-MBP.lan"
}
```
