### ISSUE TITLE
Date filter issues could not use log date

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-date#18]
(This issue was originally filed by @waleedsaud at https://github.com/elastic/logstash/issues/2194)

---

Date filter did not work for me on netscreen firewall logs and this is my config:

```
input {
  tcp { 
    type => "J-NS5400-5"
    port => 3333
  } 
}

filter {
  if [type] == "J-NS5400-5" {
    grok {
      
      match => { "message" =>"%{NETSCREENSESSIONLOG}"}
    }

    date {

      match => [ "date", "MMM dd HH:mm:ss" ]
      timezone => "Asia/Riyadh"
      locale => "en_SA"

    }
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
   embedded => true
  }
}

```

**Comment by purbon** [comment]
Tested this with the last version of this plugin and can not reproduce. closing this for now, feel free to reopen in case the issue surfaces again. Thank for your contribution.
