### ISSUE TITLE
Allow dynamic parsing of the timezone parameter to date filter

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-date#23]
(This issue was originally filed by @robinsmidsrod at https://github.com/elastic/logstash/issues/1685)

---

I'm using beaver to ship nginx error log to logstash, and it has an additional field with the timezone information from the server. I'd like to use the specified timezone to parse the timestamp properly.

```
if [tz] {
 date {
  match => [ "nginx_datestamp", "yyyy/MM/dd HH:mm:ss" ]
  timezone => "%{tz}"
  target => "nginx_timestamp"
 }
}
```

**Comment by jordansissel** [comment]
I agree this is a good idea.

**Comment by purbon** [comment]
duplicated of #15

**Comment by vishwastyagi** [comment]
Hi Everyone,
I am not to use date filter like the way mentioned above.
Help is required.
I have an xml which I am pushing into elasticsearch from logstash

2016-09-23

My filter is:

filter{

mutate {
add_field => [ "nginx_timestamp", "/RECORD/DATE/text()" ]
}
date {
match => [ "nginx_timestamp", "yyyy-MM-dd" ]
}
mutate {
remove_field => [ "nginx_timestamp" ]
}

}

I am getting warning in logstash saying:

"Failed parsing date from field {:field=>"nginx_timestamp", :value=>"/RECORD/DATE/text()", :exception=>"Invalid format: \"/RECORD/DATE/text()\"", :config_parsers=>"yyyy-MM-dd", :config_locale=>"default=en_IN", :level=>:warn}
"

And kibana is showing current date in @timestamp

Please help if I am missing anything.

**Comment by wiibaa** [comment]
@vishwastyagi Please raise your usage question to https://discuss.elastic.co/c/logstash and you will receive support there
