### ISSUE TITLE
Add option to handle dates without year when going from Dec 31st to Jan 1st

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-filter-date#33]
Quite a few programs emit, by default, logs without any year in them. This is usually not a problem, unless a log from Dec 31 arrives just after midnight (on January 1st), the wrong year will be used and the log will be in the future.

Right now, for those applications, I have a lengthy and ugly workaround involving ruby and mutate filter before date is applied. Basically, what it does is check if the log is in the future and if it is by a certain amount of time, the previous year is used. Then mutate will append it back to the timestamp string before the date filter runs.

It would be nice if there was an option to deal with that kind of thing such as:
```
use_current_year_if_within_days => 31
```

which would use the current year if the log date (after successful parsing into timestamp) if in the future with a maximum of 31 days. After that, it would use the previous year.

**Comment by jordansissel** [comment]
Yeah this problem seems to happen every year, we'll see to it that it gets fixed before newyears ;P

**Comment by jsvd** [comment]
possible fix here https://github.com/logstash-plugins/logstash-filter-date/pull/4 :)
its performance impact hasn't been tested yet, and I recall that the specs would sometimes fail

**Comment by purbon** [comment]
@jsvd speaks still fail for me, we need to find why they are failing.

**Comment by purbon** [comment]
Related to #3

**Comment by jsvd** [comment]
fixed in #4
