### ISSUE TITLE
Parse failures incur a significant performance penalty

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-date#41]
Related to #5.

A discussion with @sherry-ger today reminded me of an old problem with the date filter. I did some experiments here with respect to date filter performance during a failed match.

Some sample code to test the cost of a certain number of parse failures when multiple matches are given:

``` ruby
require "logstash/filters/date"
require "logstash/event"
require "benchmark"

iterations = 10_000
puts "Loop count: #{iterations}"
Benchmark.bmbm do |r|
  10.times do |i|
    patterns = [ *i.times.map { "YYYY" }, "ISO8601" ]
    date = LogStash::Filters::Date.new("match" => [ "foo", *patterns ])
    date.register

    r.report("YYYY(#{i}), ISO8601") do
      iterations.times do 
        event = LogStash::Event.new("foo" => "2001-01-01T08:00:00.000Z")
        date.filter(event)
      end
    end
  end
end
```

The performances gets significantly worse as the number of failed parses per-event increases.

```
YYYY(0), ISO8601   0.270000   0.000000   0.270000 (  0.270000)
YYYY(1), ISO8601   3.060000   0.020000   3.080000 (  2.944000)
YYYY(2), ISO8601   5.830000   0.060000   5.890000 (  6.164000)
YYYY(3), ISO8601   8.300000   0.060000   8.360000 (  8.663000)
YYYY(4), ISO8601  11.380000   0.090000  11.470000 ( 11.204000)
...
```

With 0 failures, speed is fairly fast (0.27 seconds for 10,000 events; ~37,000 per second). At 1 failure, we slow down _significantly_ (90%!!!) and it gets worse at 2 failures, then 3, etc.

Sampling cpu with visualvm shows this:

<img width="891" alt="screen shot 2015-12-01 at 7 45 22 pm" src="https://cloud.githubusercontent.com/assets/131818/11521838/531affd0-9865-11e5-808b-632a476a26c3.png">

Joda will raise an exception if the time parse fails, and JRuby will wrap this exception before handing it to our code. It appears most of the time is spent generating the stack trace - something we don't even _use_ in most cases. Funky.

This phenomenon is mentioned on [JRuby's performance tips page](https://github.com/jruby/jruby/wiki/PerformanceTuning#common-profiling-hotspots) and on a recent [JRuby blog entry about rescue/exception performance](http://blog.jruby.org/2015/10/performance_improvements_in_jruby_9030/).

Some thoughts for next steps:
- See if we can avoid using exceptions for failure detection
- See if JRuby 9.0.3.0 fixes this

**Comment by jordansissel** [comment]
> See if we can avoid using exceptions for failure detection

All the Joda DateTimeFormatter methods that do parsing seem to raise IllegalArgumentException on failure and I didn't find any way to check if a time string matched as a valid format without an exception.

**Comment by jordansissel** [comment]
JRuby 9.0.3.0 still appears to be affected

```
% rvm jruby-9.0.3.0 do bundle exec ruby -I./lib ./foo.rb
<removed the rehearsal run>

                       user     system      total        real
YYYY(0), ISO8601   0.270000   0.000000   0.270000 (  0.262851)
YYYY(1), ISO8601   2.910000   0.000000   2.910000 (  2.923718)
YYYY(2), ISO8601   5.500000   0.020000   5.520000 (  5.541866)
YYYY(3), ISO8601   8.020000   0.020000   8.040000 (  8.009971)
YYYY(4), ISO8601  10.790000   0.040000  10.830000 ( 10.831098)
YYYY(5), ISO8601  14.140000   0.090000  14.230000 ( 15.677630)
YYYY(6), ISO8601  17.270000   0.130000  17.400000 ( 18.894410)
```

**Comment by jordansissel** [comment]
I think we'll have to solve this by wrapping up some of the date filter's behavior into a Java library. The date filter could use a bit of love and refactoring, anyway, so this is a good excuse to apply some love.

**Comment by gmoskovicz** [comment]
@jordansissel 

looks like this issue gets obvious when you have a date filter like the following:

```
 date {
    match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
  }
```

This filter will be faster from the 1 to the 9 of the month, but when you have two-day format it gets worse. We are going to fail at least 1 time per message since the first matching will always fail in 30% of the month, killing logstash's performance. I am going to make some extra investigation to post some results here.

**Comment by gmoskovicz** [comment]
## Date filter with failing 
----------------------------
```
  date {
    match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    target => "timestamp_2"
  }
```
----------------------------

508,032 documents
11:51:15 - 11:52:43 = 88 seconds
Average Rate: 5700 documents per seconds


## Date filter whithout failing 
----------------------------
```
  date {
    match => [ "syslog_timestamp", "MMM dd HH:mm:ss" ]
    target => "timestamp_2"
  }
```
----------------------------

508,032 documents
12:03:15 - 12:04:19 = 64 seconds
Average Rate: 7900 documents per seconds

Just by removing a failed date expression we got a ~40% performance gain.

Honestly i didn't notice such a high impact of the performance in this test while the number of failed messages starts increasing, but i did noticed that in the second test the first couple of seconds we got more than 8k EPS, and at the end it was between 5.500 and 7.500. I expect this to be worse when there are 18 file being read, and multiple workers per thread.

**Comment by jordansissel** [comment]
#71 fixes this.
