### ISSUE TITLE
The "fallback parser to english" does not correct the year

### ISSUE THREAD

**Issue by madidier** [logstash-plugins/logstash-filter-date#57]
The [english parser](https://github.com/logstash-plugins/logstash-filter-date/blob/master/lib/logstash/filters/date.rb#L205) used as a fallback when the locale's language is not english does not automatically correct the year as the main one does. This can be quite confusing as the examples given in the documentation do not explicitly specify a locale, and are, therefore, system-dependent.

**Comment by wiibaa** [comment]
It was also found out in https://discuss.elastic.co/t/date-filter-stuck-in-2000/43103 that the fallback parser used with syslog pattern (missing year) set the date to 2000

**Comment by wiibaa** [comment]
published in 3.0.1

@suyograo can you close please
