### ISSUE TITLE
Fails to parse a timestamp that would be next years DST switchover for CET

### ISSUE THREAD

**Issue by Xylakant** [logstash-plugins/logstash-filter-date#62]
This is a bit a weird one and took me a bit to debug. The date filter fails to parse a timestamp that would be next years DST switchover for CET (and thus won't exist) if no explicit date is given. It's probably best explained by a testcase. The following test fails:
  
    describe "don't fail on next years DST switchover in CET" do
      config <<-CONFIG
        filter {
          date {
            match => [ "message", "MMM dd HH:mm:ss" ]
            locale => "en"
            timezone => "CET"
          }
        }
      CONFIG
  
      before(:each) do
        logstash_time = Time.utc(2016,03,29,23,59,50)
        allow(Time).to receive(:now).and_return(logstash_time)
      end
  
      sample "Mar 26 02:00:37" do
        insist { subject["tags"] } != ["_dateparsefailure"]
        insist { subject["@timestamp"].to_s } == "2016-03-26T01:00:37.000Z"
      end
    end
  
The 26th of march 2017 is when the DST change to summertime will happen, so the time 02:00:37 won't exist. Notably a timestamp that is before 02:00:00 or after 03:00:00 does work and returns the expected date/time in 2016. Also the following testcase works without a hitch.

  
    describe "don't fail on next years DST switchover in CET" do
      config <<-CONFIG
        filter {
          date {
            match => [ "message", "yyyy MMM dd HH:mm:ss" ]
            locale => "en"
            timezone => "CET"
          }
        }
      CONFIG
  
      before(:each) do
        logstash_time = Time.utc(2016,03,29,23,59,50)
        allow(Time).to receive(:now).and_return(logstash_time)
      end
  
      sample "2016 Mar 26 02:00:37" do
        insist { subject["tags"] } != ["_dateparsefailure"]
        insist { subject["@timestamp"].to_s } == "2016-03-26T01:00:37.000Z"
      end
    end

**Comment by wiibaa** [comment]
@Xylakant good catch, the code is different when no year is present in the pattern and it must be changed to behave similarly than joda parser
