### ISSUE TITLE
How to filter tweets based on date ?

### ISSUE THREAD

**Issue by DBARUNNER** [logstash-plugins/logstash-filter-date#79]
i use logstash_twitter_input plugin to get data i have a field by the name @timestam => 2011-11-16T03:44:01.103Z now i want to filter it with logstash_date_filter plugin to get new data not old data for exampe today date is 2011-11-16T03:44:01.103Z and i want get just tweets that @timestamp match to 2011-11-16T03:44:01.103Z not tweets that have @timestamps = 2011-11-15T03:44:01.103Z

her is my logstash_filter_date plugin code
filter {
date
{
match => ['timestamp' => "MMM d YYY HH:mm:ss", "ISO8601"]
}
}

but i get old tweets as weel .
help me to just get new tweets, i have asked from stackoverflow no one answear me that's why i asked from you please help

**Comment by jordansissel** [comment]
I recommend you ask questions like this on our community support forum, https://discuss.elastic.co/
