### ISSUE TITLE
Feature Request: Be able to drop events outside of time window

### ISSUE THREAD

**Issue by izhou99** [logstash-plugins/logstash-filter-date#81]
It would be nice to be able to specify a time window in this plugin. If an event falls outside of the window, the event will be dropped

**Comment by jordansissel** [comment]
I like the idea, but for this specific request, I think this is outside the scope of the date filter. The purpose of the date filter is to take some text input and parse it into a time value a computer can do useful things with.

Dropping things older than a given date is probably best done in a new filter.
