### ISSUE TITLE
_dateparsefailure on previously valid UNIX timestamp

### ISSUE THREAD

**Issue by almico** [logstash-plugins/logstash-filter-date#86]
- Version: logstash 5.1.1
- Operating System: CentOS Linux release 7.3.1611 (Core)
- Java version: java version "1.8.0_112"
- Sample Data: 1484175605.258932

I was successfully parsing ts=1484175605.258932 as a UNIX timestamp, using

```
      date {
        match => [ "ts", "UNIX" ]
        target => "@timestamp"
      }
```

with logstash 5.0.2.
I just upgraded to logstash 5.1.1 and now, with exactly the same timestamp, I get "_dateparsefailure".

**Comment by jsvd** [comment]
Strange, I can't seem to replicate your issue:

```
/tmp/logstash-5.1.1 % echo "1484175605.258932" | bin/logstash -e 'filter { date { match => ["message", "UNIX"] target => "@timestamp" } }' 
{
    "@timestamp" => 2017-01-11T23:00:05.258Z,
      "@version" => "1",
          "host" => "Joaos-MBP-5",
       "message" => "1484175605.258932",
          "type" => "stdin",
          "tags" => []
}
```

**Comment by almico** [comment]
Interesting indeed.
Your code works. Mine is buried in a filebeat sent to a logstash that then converts the message with the json filter and can handle multiple data types.
Everything was working perfectly with 5.0.2.
I will try to strip everything else to see what causes this issue.
Will be back asap :-)

**Comment by almico** [comment]
Ok, I think I found the cause:
I had to add the following code to make it work:

```
    mutate {
      convert => { "ts" => "float" }
    }
```

Before applying this fix, rubydebug was reporting "ts" as a float, I think. This is its output:

```
"ts" => 1484175605.258932
```

And now that I am using mutate to make sure the type is "float", rubydebug shows "ts" exactly like before.
Anyway: I still think that logstash 5.1 should be able to handle my sample unix timestamp as it properly did in 5.0 :smile:

**Comment by almico** [comment]
The following returns "_dateparsefailure":
```
echo '{"ts":1484175605.258932}' | /usr/share/logstash/bin/logstash -e 'filter { json { source => "message" } date { match => ["ts", "UNIX"] target => "@timestamp" } }'
```
And the following works fine:
```
echo '{"ts":1484175605.258932}' | /usr/share/logstash/bin/logstash -e 'filter { json { source => "message" } mutate { convert => { "ts" => "float" } } date { match => ["ts", "UNIX"] target => "@timestamp" } }'
```

I hope I copied everything properly.

**Comment by jsvd** [comment]
Strange again..in my first example the message was a string, and now I tried converting it first to float:

```
/tmp/logstash-5.1.1 % echo "1484175605.258932" | bin/logstash -e 'filter { mutate { convert => { "message" => "float" } } date { match => ["message", "UNIX"] target => "@timestamp" } }'
{
    "@timestamp" => 2017-01-11T23:00:05.258Z,
      "@version" => "1",
          "host" => "Joaos-MBP-5",
       "message" => 1484175605.258932,
          "type" => "stdin",
          "tags" => []
}
```

**Comment by jsvd** [comment]
@almico ahh! awesome, a failing case! thank you, let me investigate

**Comment by almico** [comment]
:smile:

**Comment by jsvd** [comment]
Interesting, so the number is being loaded from json as a BigDecimal:

```
> LogStash::Json.load '{"ts":1484175605.258932}'
 => {"ts"=>#<BigDecimal:469dd4b2,'0.1484175605258932E10',16(20)>} 
```

Checking why date filter doesn't handle this well

**Comment by almico** [comment]
Does it mean that I hit a bigger issue, actually?

**Comment by jsvd** [comment]
@almico it is a nice find, and it is contained in the filter date, not a problem in core.

So, the json loader converts that number into a BigDecimal (both in logstash 5.1 and 5.0), but the date filter had a rewrite in java which is included in logstash 5.1

In this rewrite, the method responsible for parsing is overloaded for different classes like [String](https://github.com/logstash-plugins/logstash-filter-date/blob/master/src/main/java/org/logstash/filters/parser/UnixEpochParser.java#L28), [Long](https://github.com/logstash-plugins/logstash-filter-date/blob/master/src/main/java/org/logstash/filters/parser/UnixEpochParser.java#L60) and [Double](https://github.com/logstash-plugins/logstash-filter-date/blob/master/src/main/java/org/logstash/filters/parser/UnixEpochParser.java#L65).

I think that the lack of an overloaded version of `parse` for BigDecimal is creating this issue.

**Comment by almico** [comment]
Great to hear that.
Thank you for looking into it.

**Comment by jordansissel** [comment]
@almico Thank you for so much great detail and work to isolate this problem :)

**Comment by jordansissel** [comment]
@jsvd This PR fixes the compile problem you and I hit: https://github.com/logstash-plugins/logstash-filter-date/pull/87

**Comment by almico** [comment]
Thank you for the quick reaction 😃

**Comment by jordansissel** [comment]
@almico I'm planning to fix this today or tomorrow; I'll add test coverage for this so that it doesn't break in the future <3

**Comment by jordansissel** [comment]
I was looking through the test suite, and we actually test this particular kind of number *BUT* we don't test it having come through the JSON parser, oops.

Here's the test we have for this:

```
    #Support float values
    sample("mydate" => 1350414944.123456) do
      insist { subject.get("mydate") } == 1350414944.123456
      insist { subject.get("@timestamp").time } == Time.iso8601("2012-10-16T12:15:44.123-07:00").utc
    end
```

I'll update this to add BigDecimal support.
