### ISSUE TITLE
Multiple input fields to 1 date

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-filter-date#9]
migrated from https://logstash.jira.com/browse/LOGSTASH-1956

Full text below:

Lets say I have 2 fields: date and time.
When I try to match these with the date filter, it won't work.

```
date { 
  match => [ "date", "yyyy-MM-dd", "time", "HH:mm:ss.SSS" ]
}
```

According to lieter in IRC (thank you!) I can use the mutate filter to solve that by creating an artificial "merged field":
```
mutate { add_field => ["bla", "%{date} %{time}"] }
```
This is a entirely unnecessary second step which further complicates the issue one has with malformed logs like:
{DAY:day} {MONTH:month} {MONTHDAY:monthday} {TIME:time} {WORD:timezone} {YEAR:year}
This might be already possible and just undocumented: http://logstash.net/docs/1.3.3/filters/date#match
I also tried to google it, but no success.
Thank you for listening.

**Comment by jsvd** [comment]
Honestly I don't see the problem with the extra step with mutate. Also having multiple inputs would solve the issue when filed A has DAY and field B has MONTHDAY (not sure if that's the problem).

**Comment by electrical** [comment]
The reason the initial solution fails is that its unsupported.
We only support a single source field and multiple patterns.
One could use the add_field option in the grok filter ( when using that ) to compile the required field with the date and time values.

**Comment by jsvd** [comment]
maybe I didn't carry the correct meaning when migrating the issue here
the idea is to add this feature.

Isn't the add_field invoked after the filter has done it's work?

**Comment by electrical** [comment]
add_field is indeed done after it yeah. but since the date filter is done after the grok filter, adding the add_field option to the grok filter would solve it.

**Comment by jsvd** [comment]
I misread, correct :+1:

**Comment by purbon** [comment]
I agree with @electrical I don't think we should implement this kind of feature, we've wither grok or mutate to compose the right timestamp format.

Closing this for now, we might reopen if something new surfaces.
