### ISSUE TITLE
discard cancelled events in multi_filter

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-filter-date#90]
because of the way the pipeline handles a list/batch of events, the Filter#multi_filter(events) method will receive a list of events and some of them can already be cancelled.

Since most filters implement the `Filter#filter(event)` api, this ignoring of the cancelled events [is done automatically](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/filters/base.rb#L162) in the base class implementation of `multi_filter`.

However, if a filter directly defines this `multi_filter` method (like the filter date plugin does), it must reject the cancelled events otherwise it will, in this case, try to parse dates on cancelled events wasting cpu cycles.

**Comment by colinsurprenant** [comment]
fixed by #93 and published as v3.1.5
